# Available both on server and client.
api_endpoint: https://api.hive.blog
app_name: blog
images_endpoint: https://images.hive.blog
logging_browser_enabled: false
logging_log_level: info
site_domain: https://blog.openhive.network
wallet_endpoint: https://wallet.openhive.network

# Available on server only.
server:
  secret_cookie_password: 2gyZ3GDw3LHZKCMEPmPDL3sjREVRXPr1
