stages:
  - build
  - replay-and-sync
  - test
  - test-report-aggregate
  - deploy
  - publish
  - cleanup

variables:
  # Variables required by Common CI jobs
  CI_COMMON_JOB_VERSION: 'e74d7109838ff05fdc239bced6a726aa7ad46a9b'
  DOCKER_BUILDER_TAG: '$CI_COMMON_JOB_VERSION'
  DOCKER_DIND_TAG: '$CI_COMMON_JOB_VERSION'
  IMAGE_REMOVER_TAG: '$CI_COMMON_JOB_VERSION'

  # Git settings
  GIT_DEPTH: 20
  GIT_SUBMODULE_STRATEGY: none
  GIT_STRATEGY: clone

  # Runner feature flags
  FF_ENABLE_JOB_CLEANUP: 1

  # HAF API node configuration
  API_NODE_VERSION: "1.27.8"
  API_NODE_TAG: "denser-11"
  HAF_IMAGE_REGISTRY: "registry.gitlab.syncad.com/hive/haf/mirrornet-instance"
  HAF_IMAGE_NAME: "${HAF_IMAGE_REGISTRY}:${API_NODE_VERSION}"
  BLOCK_LOG_VERSION: "f8a89045"
  # BLOCK_LOG_SOURCE_DIR: "/blockchain/block_log_mirror_44"
  REPLAY_DIRECTORY_PREFIX: "/cache/replay_data_denser_haf_api_node"
  REPLAY_DIRECTORY: "${REPLAY_DIRECTORY_PREFIX}_${API_NODE_TAG}_${API_NODE_VERSION}_${BLOCK_LOG_VERSION}"
  REPLAY_PIPELINE_DIRECTORY: "${REPLAY_DIRECTORY_PREFIX}_${CI_PIPELINE_ID}"
  DOCKER_TLS_CERTDIR: "${REPLAY_PIPELINE_DIRECTORY}_certs"
  BLOCK_LOG_SOURCE: "${REPLAY_PIPELINE_DIRECTORY}_block_log"
  BLOCK_LOG_SOURCE_DIR: "${BLOCK_LOG_SOURCE}"

  # Other settings
  CADDY_TAG: "2.7.6"
  PLAYWRIGHT_TAG: "v1.49.1-jammy"

include:
  - template: Workflows/Branch-Pipelines.gitlab-ci.yml
  - project: 'hive/common-ci-configuration'
    ref: e74d7109838ff05fdc239bced6a726aa7ad46a9b
    file: 
      - '/templates/docker_image_jobs.gitlab-ci.yml'
      - '/templates/cache_cleanup.gitlab-ci.yml'
  - local: 'environments/common.yml'
  - local: 'environments/develop.yml'
  - local: 'environments/production.yml'
  - local: 'templates/denser-deploy.yml'
  - project: 'hive/haf'
    ref: b7870f229cc0d45993a648ab9a15b0b4a12e7fe5 #develop
    file: '/scripts/ci-helpers/prepare_data_image_job.yml'    
  - project: 'hive/haf_api_node'
    ref: denser-11
    file: 'ci/node-replay.gitlab-ci.yml'  

.docker_build_template:
  extends: .docker_image_builder_job_template
  stage: build
  before_script:
    - !reference [.docker_image_builder_job_template, before_script]
    - |
      echo -e "\e[0Ksection_start:$(date +%s):login[collapsed=true]\r\e[0KLogging to Docker registry..."
      docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
      echo -e "\e[0Ksection_end:$(date +%s):login\r\e[0K"
  script: scripts/ci-helpers/docker-build-template-script.sh
  artifacts:
    paths:
      - ${TURBO_APP_NAME}-docker-build.env
    reports:
      dotenv: ${TURBO_APP_NAME}-docker-build.env
  tags:
    - public-runner-docker
    - hived-for-tests

mirrornet-haf-binaries-extraction:
  extends: .job-defaults
  stage: build
  image:
    name: $HAF_IMAGE_NAME
    entrypoint: [ "" ]
  variables:
    BINARY_CACHE_PATH: "${CI_PROJECT_DIR}/hived-mirrornet-binaries"
    GIT_SUBMODULE_STRATEGY: recursive
  script: "cp --recursive /home/hived/bin ${BINARY_CACHE_PATH}"
  artifacts:
    when: on_success
    paths:
      - "${BINARY_CACHE_PATH}"
  tags:
    - public-runner-docker
    - hived-for-tests

docker-build-auth:
  extends: .docker_build_template
  variables:
    TURBO_APP_SCOPE: '@hive/auth'
    TURBO_APP_PATH: '/apps/auth'
    TURBO_APP_NAME: 'auth'

docker-build-blog:
  extends: .docker_build_template
  variables:
    TURBO_APP_SCOPE: '@hive/blog'
    TURBO_APP_PATH: '/apps/blog'
    TURBO_APP_NAME: 'blog'

docker-build-wallet:
  extends: .docker_build_template
  variables:
    TURBO_APP_SCOPE: '@hive/wallet'
    TURBO_APP_PATH: '/apps/wallet'
    TURBO_APP_NAME: 'wallet'

# Hived binary built as a part of HAF requires an additional
# library to function. This library has to be extracted from
# the image and passed to job extended_block_log_creation.
library_extraction:
  extends: .job-defaults
  stage: build
  image:
    name: $HAF_IMAGE_NAME
    entrypoint: [ "" ]
  needs:
    - job: "mirrornet-haf-binaries-extraction"
      artifacts: true
  variables:
    BINARY_CACHE_PATH: "${CI_PROJECT_DIR}/hived-mirrornet-binaries"
  script: scripts/ci-helpers/library-extraction.sh
  artifacts:
    when: on_success
    paths:
      - "${BINARY_CACHE_PATH}"
  tags:
    - public-runner-docker

extended_block_log_creation:
  extends: .extended_block_log_creation
  stage: build
  needs:
    - job: "mirrornet-haf-binaries-extraction"
      artifacts: true
    - job: "library_extraction"
      artifacts: true 
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    REGISTRY: "registry.gitlab.syncad.com/hive/hive"
    REGISTRY_USER: "${HIVED_CI_IMGBUILDER_USER}"
    REGISTRY_PASS: "${HIVED_CI_IMGBUILDER_PASSWORD}"
    IMAGE_TAG: "${BLOCK_LOG_VERSION}"
    HIVE_SRC: "${CI_PROJECT_DIR}/haf/hive"
    HIVE_COMMIT: "${BLOCK_LOG_VERSION}"
    BLOCK_LOG_SOURCE_DIR: "/blockchain/block_log_5m"
    BINARY_PATH: "${CI_PROJECT_DIR}/hived-mirrornet-binaries"
    LD_LIBRARY_PATH: "${BINARY_PATH}"
  tags:
    - public-runner-docker
    - hived-for-tests

block-log-extraction:
  extends: .docker_image_builder_job_template
  stage: replay-and-sync
  needs:
    - extended_block_log_creation
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    BLOCK_LOG_DIRECTORY: "${REPLAY_PIPELINE_DIRECTORY}_block_log"
  script: scripts/ci-helpers/block-log-extraction.sh
  tags:
    - data-cache-storage

block_log_processing:
  extends: .job-defaults
  image: "registry.gitlab.syncad.com/hive/hive/ci-base-image${TEST_IMAGE_TAG}"
  stage: replay-and-sync
  needs:
    - mirrornet-haf-binaries-extraction
    - block-log-extraction
  variables:
    BLOCK_LOG_UTIL_PATH: "${CI_PROJECT_DIR}/hived-mirrornet-binaries/block_log_util"
  script: scripts/ci-helpers/block-log-processing.sh
  artifacts:
    reports:
      dotenv:
        - "block_log_data.env" 
    paths:
      - "*.log"
      - "block_log_data.env"
  tags:
    - data-cache-storage

mirrornet-haf-node-replay:
  extends: .haf-node-replay
  stage: replay-and-sync
  timeout: 3 hours
  needs:
    - mirrornet-haf-binaries-extraction
    - block_log_processing
  variables:
    GIT_STRATEGY: "clone"
    CI_DEBUG_SERVICES: "false" # Change to true to debug services in this job
    # LAST_BLOCK_NUMBER: "5004741"
    ARGUMENTS: "--chain-id=44 --skeleton-key=5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n --replay-blockchain --stop-at-block ${LAST_BLOCK_NUMBER} --alternate-chain-spec=/home/hived/datadir/blockchain/alternate-chain-spec.json"
    # FAKETIME: "@2016-09-16 01:39:06"
    FAKETIME: ${HEAD_BLOCK_TIMESTAMP}
    ADDITIONAL_CONFIGURATION_SCRIPT: "scripts/ci-helpers/copy-mirrornet-haf-config.sh"
    REPLAY_TIMEOUT: 9000
    HAF_IMAGE: ${HAF_IMAGE_REGISTRY}
    HIVE_API_NODE_VERSION: ${API_NODE_VERSION}
  tags:
    - data-cache-storage

mirrornet-replay-data-copy:
  extends: .job-defaults
  stage: replay-and-sync
  needs:
    - mirrornet-haf-node-replay
  image: "registry.gitlab.syncad.com/hive/hive/ci-base-image${TEST_IMAGE_TAG}"
  script: scripts/ci-helpers/copy-replay-data.sh
  variables:
    REPLAY_SOURCE: "${REPLAY_PIPELINE_DIRECTORY}"
    REPLAY_DESTINATION: "${REPLAY_DIRECTORY}"
  tags:
    - data-cache-storage

.node-job:
  extends: .job-defaults
  image:
    name: node:20.11.1-alpine3.18
    entrypoint: []
  stage: test
  before_script:
    - corepack enable
    - corepack prepare pnpm@9.6.0 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - |
      echo -e "\e[0Ksection_start:$(date +%s):deps[collapsed=true]\r\e[0KInstalling dependencies..."
      pnpm install --frozen-lockfile
      echo -e "\e[0Ksection_end:$(date +%s):deps\r\e[0K"
  cache:
    key: '$TURBO_APP_SCOPE-cache-2'
    paths:
      - .npm/
      - .pnpm-store/
      - .next/
  artifacts:
    name: '$CI_JOB_NAME-$CI_COMMIT_REF_NAME'
    when: always
    expire_in: 1 week
  tags:
    - public-runner-docker

.e2e_tests_template:
  image: "mcr.microsoft.com/playwright:${PLAYWRIGHT_TAG}"
  stage: test
  variables:
    REACT_APP_API_ENDPOINT: "https://api.hive.blog"
    REACT_APP_IMAGES_ENDPOINT: "https://images.hive.blog/"
    REACT_APP_CHAIN_ID: "beeab0de00000000000000000000000000000000000000000000000000000000"
    REACT_APP_LOGGING_BROWSER_ENABLED: "true"
    NODE_TLS_REJECT_UNAUTHORIZED: 0
  script:
    - cd "apps/${APP_NAME}"
    - npm run test:e2e
  artifacts:
    when: always
    paths:
      - "apps/${APP_NAME}/playwright-report/"
      - "apps/${APP_NAME}/test-results/"
    reports:
      junit: "apps/${APP_NAME}/junit/results.xml"

e2e-tests-blog:
  extends: .e2e_tests_template
  needs:
    - docker-build-blog
  variables:
    APP_NAME: blog

e2e-tests-wallet:
  extends: .e2e_tests_template
  needs:
    - docker-build-wallet
  variables:
    APP_NAME: wallet

e2e-tests-auth:
  extends: .e2e_tests_template
  needs:
    - docker-build-auth
  variables:
    APP_NAME: auth

# Development Mainnet Deployments
deploy:dev:auth:mainnet:
  extends: 
    - .denser_deploy_template
    - .develop_mainnet
  needs:
    - docker-build-auth
    - e2e-tests-auth
  variables:
    APP_NAME: auth
    PORT: $AUTH_PORT
    CONTAINER_NAME: denser-dev-auth-mainnet

deploy:dev:blog:mainnet:
  extends: 
    - .denser_deploy_template
    - .develop_mainnet
  needs:
    - docker-build-blog
    - e2e-tests-blog
  variables:
    APP_NAME: blog
    PORT: $BLOG_PORT
    CONTAINER_NAME: denser-dev-blog-mainnet

deploy:dev:wallet:mainnet:
  extends: 
    - .denser_deploy_template
    - .develop_mainnet
  needs:
    - docker-build-wallet
    - e2e-tests-wallet
  variables:
    APP_NAME: wallet
    PORT: $WALLET_PORT
    CONTAINER_NAME: denser-dev-wallet-mainnet

# Production Mainnet Deployments
deploy:prod:auth:mainnet:
  extends: 
    - .denser_deploy_template
    - .production_mainnet
  needs:
    - docker-build-auth
    - e2e-tests-auth
  variables:
    APP_NAME: auth
    PORT: $AUTH_PORT
    CONTAINER_NAME: denser-prod-auth-mainnet

deploy:prod:blog:mainnet:
  extends: 
    - .denser_deploy_template
    - .production_mainnet
  needs:
    - docker-build-blog
    - e2e-tests-blog
  variables:
    APP_NAME: blog
    PORT: $BLOG_PORT
    CONTAINER_NAME: denser-prod-blog-mainnet

deploy:prod:wallet:mainnet:
  extends: 
    - .denser_deploy_template
    - .production_mainnet
  needs:
    - docker-build-wallet
    - e2e-tests-wallet
  variables:
    APP_NAME: wallet
    PORT: $WALLET_PORT
    CONTAINER_NAME: denser-prod-wallet-mainnet

# Development Mirrornet Deployments
deploy:dev:auth:mirrornet:
  extends: 
    - .denser_deploy_template
    - .develop_mirrornet
  needs:
    - docker-build-auth
    - e2e-tests-auth
    - mirrornet-based-tests
  variables:
    APP_NAME: auth
    PORT: $AUTH_PORT
    CONTAINER_NAME: denser-dev-auth-mirrornet

deploy:dev:blog:mirrornet:
  extends: 
    - .denser_deploy_template
    - .develop_mirrornet
  needs:
    - docker-build-blog
    - e2e-tests-blog
    - mirrornet-based-tests
  variables:
    APP_NAME: blog
    PORT: $BLOG_PORT
    CONTAINER_NAME: denser-dev-blog-mirrornet

deploy:dev:wallet:mirrornet:
  extends: 
    - .denser_deploy_template
    - .develop_mirrornet
  needs:
    - docker-build-wallet
    - e2e-tests-wallet
    - mirrornet-based-tests
  variables:
    APP_NAME: wallet
    PORT: $WALLET_PORT
    CONTAINER_NAME: denser-dev-wallet-mirrornet

# Production Mirrornet Deployments
deploy:prod:auth:mirrornet:
  extends: 
    - .denser_deploy_template
    - .production_mirrornet
  needs:
    - docker-build-auth
    - e2e-tests-auth
    - mirrornet-based-tests
  variables:
    APP_NAME: auth
    PORT: $AUTH_PORT
    CONTAINER_NAME: denser-prod-auth-mirrornet

deploy:prod:blog:mirrornet:
  extends: 
    - .denser_deploy_template
    - .production_mirrornet
  needs:
    - docker-build-blog
    - e2e-tests-blog
    - mirrornet-based-tests
  variables:
    APP_NAME: blog
    PORT: $BLOG_PORT
    CONTAINER_NAME: denser-prod-blog-mirrornet

deploy:prod:wallet:mirrornet:
  extends: 
    - .denser_deploy_template
    - .production_mirrornet
  needs:
    - docker-build-wallet
    - e2e-tests-wallet
    - mirrornet-based-tests
  variables:
    APP_NAME: wallet
    PORT: $WALLET_PORT
    CONTAINER_NAME: denser-prod-wallet-mirrornet

buildkit_cache_cleanup:
  stage: cleanup
  extends: .buildkit_cleanup_job_template
  needs: []
  variables:
    CACHE_REPOSITORIES: "auth/cache,blog/cache,wallet/cache"

# Deletes replay data used by the tests and created by mirrornet-replay-data-copy
cleanup_haf_api_node_pipeline_cache:
  needs:
    - mirrornet-replay-data-copy
    - mirrornet-based-tests
  extends: 
    - .cleanup_cache_manual_template
  stage: cleanup
  variables:
    CLEANUP_PATH_PATTERN: "${REPLAY_PIPELINE_DIRECTORY}*"
  when: always
  tags:
    - data-cache-storage

# Deletes all HAF API node replay data
cleanup_haf_api_node_cache_manual:
  extends: 
    - .cleanup_cache_manual_template
  needs: []
  stage: cleanup
  variables:
    CLEANUP_PATH_PATTERN: "${REPLAY_DIRECTORY_PREFIX}*"
  tags:
    - data-cache-storage

# Deletes HAF API node replay data older than 7 days
cleanup_old_haf_api_node_cache:
  extends:
    - .cleanup_old_cache_template
  needs: []
  stage: cleanup
  variables:
    CLEANUP_PATH_PATTERN: "${REPLAY_DIRECTORY_PREFIX}*"
  tags:
    - data-cache-storage

mirrornet-based-tests:
  extends: 
    - .haf_api_node_test
    - .node-job
  needs:
    - mirrornet-haf-binaries-extraction
    - docker-build-auth
    - docker-build-blog
    - docker-build-wallet
    - mirrornet-replay-data-copy
    - block_log_processing
  image: "mcr.microsoft.com/playwright:${PLAYWRIGHT_TAG}"
  services:
    - name: $BLOG_IMAGE_NAME
      alias: denser-blog
      variables:
        HEALTHCHECK_TCP_PORT: '3000'
        PORT: "3000"
        REACT_APP_SITE_DOMAIN: "https://caddy-blog.local"
        REACT_APP_WALLET_ENDPOINT: "https://caddy-wallet"
        TURBO_APP_SCOPE: '@hive/blog'
        TURBO_APP_PATH: '/apps/blog'
    - name: caddy:${CADDY_TAG}
      alias: caddy-blog
      command:
        - caddy
        - reverse-proxy
        - --from=https://caddy-blog
        - --to=denser-blog:3000
        - --internal-certs
    - name: $WALLET_IMAGE_NAME
      alias: denser-wallet
      variables:
        HEALTHCHECK_TCP_PORT: '4000'
        PORT: "4000"
        REACT_APP_SITE_DOMAIN: "https://caddy-wallet.local"
        REACT_APP_BLOG_DOMAIN: "https://caddy-blog"
        TURBO_APP_SCOPE: '@hive/wallet'
        TURBO_APP_PATH: '/apps/wallet'
    - name: caddy:${CADDY_TAG}
      alias: caddy-wallet
      command:
        - caddy
        - reverse-proxy
        - --from=https://caddy-wallet
        - --to=denser-wallet:4000
        - --internal-certs
  variables:
    CI_DEBUG_SERVICES: "false"
    ARGUMENTS: "--chain-id=44 --skeleton-key=5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n --alternate-chain-spec=/home/hived/datadir/blockchain/alternate-chain-spec.json"
    FAKETIME: ${HEAD_BLOCK_TIMESTAMP}
    HAF_IMAGE: ${HAF_IMAGE_REGISTRY}
    HIVE_API_NODE_VERSION: ${API_NODE_VERSION}
    REACT_APP_API_ENDPOINT: "https://dind/"
    REACT_APP_IMAGES_ENDPOINT: "https://images.hive.blog/"
    REACT_APP_CHAIN_ID: "44"
    REACT_APP_LOGGING_BROWSER_ENABLED: "true"
    NODE_TLS_REJECT_UNAUTHORIZED: 0
  timeout: 3 hours
  script: scripts/ci-helpers/run-mirrornet-tests.sh
  after_script:
    - |
      cp "${REPLAY_PIPELINE_DIRECTORY}/docker_entrypoint.log" "${CI_PROJECT_DIR}/haf.log"
      cp --recursive "${REPLAY_PIPELINE_DIRECTORY}/logs" "${CI_PROJECT_DIR}/logs"
  cache:
    key: "mirrornet-tests-1"    
  artifacts:
    paths:
      - "*.log"
      - "logs/"
      - "*.env"
      - "apps/blog/playwright-report/"
      - "apps/blog/test-results/"
      - "apps/blog/junit/"
    reports:
      junit: "apps/blog/junit/results.xml"
  tags:
    - data-cache-storage
    - docker-build-blog