packages:
  - 'apps/*'
  - 'packages/*'

catalogs:
  # Can be referenced through "catalog:hiveio-toolset"
  hiveio-toolset:
    '@hiveio/beekeeper': 1.28.4-rc0
    '@hiveio/wax': 1.28.4-rc0
    '@hiveio/wax-signers-keychain': 1.28.4-rc0
    '@hiveio/workerbee': 1.28.4-rc0
    '@hiveio/hb-auth': 1.28.4-rc0
    '@hiveio/healthchecker-component': 1.28.4-rc0-stable.251202134057
