packages:
  - 'apps/*'
  - 'packages/*'

catalogs:
  # Can be referenced through "catalog:hiveio-toolset"
  hiveio-toolset:
    "@hiveio/beekeeper": 1.27.11
    "@hiveio/wax": 1.27.6-rc10
    "@hiveio/wax-signers-keychain": 1.27.6-rc10
    "@hiveio/workerbee": 1.27.6-rc13
    "@hiveio/hb-auth": 0.0.1-stable.250715111213
    "@hiveio/healthchecker-component": 1.0.0-stable.250715114224
