# Customer module configs
Customer:
  credit:
    initialLimit:
      # Prefix REACT_APP_, _ in place of ., __ for pascal case.
      __name: REACT_APP_CUSTOMER__CREDIT__INITIAL_LIMIT
      __format: number
