api_endpoint: REACT_APP_API_ENDPOINT
app_name: REACT_APP_APP_NAME
images_endpoint: REACT_APP_IMAGES_ENDPOINT
logging_browser_enabled: REACT_APP_LOGGING_BROWSER_ENABLED
logging_log_level: REACT_APP_LOGGING_LOG_LEVEL
site_domain: REACT_APP_SITE_DOMAIN
server:
  secret_cookie_password: REACT_APP_SERVER_SECRET_COOKIE_PASSWORD
