# Available both on server and client.
api_url: https://api.hive.blog
app_name: "Hive Auth"
images_url: https://images.hive.blog
logging_browser_enabled: false
logging_log_level: info

# Available on server only.
server:
  secret_cookie_password: 2gyZ3GDw3LHZKCMEPmPDL3sjREVRXPr8
