.production_mainnet:
  extends: .mainnet_variables
  variables:
    DOMAIN_SUFFIX: "openhive.network"
    AUTH_PORT: 8093
    BLOG_PORT: 8091
    WALLET_PORT: 8092
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

.production_mirrornet:
  extends: .mirrornet_variables
  variables:
    DOMAIN_SUFFIX: "fake.openhive.network"
    AUTH_PORT: 8193
    BLOG_PORT: 8191
    WALLET_PORT: 8192
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual 