.production_mainnet:
  extends: .mainnet_variables
  variables:
    DOMAIN_SUFFIX: "openhive.network"
    PORTS:
      AUTH: 8093
      BLOG: 8091
      WALLET: 8092
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

.production_mirrornet:
  extends: .mirrornet_variables
  variables:
    DOMAIN_SUFFIX: "fake.openhive.network"
    PORTS:
      AUTH: 8193
      BLOG: 8191
      WALLET: 8192
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual 