version: '3.9'
services:
  denser:
    image: registry.gitlab.syncad.com/hive/denser:${IMAGE_TAG:-latest}
    environment:
      - PORT
      - REACT_APP_API_ENDPOINT
      - REACT_APP_IMAGES_ENDPOINT
    ports:
      - "${PORT}:${PORT}"