name: 'denser'

services:
  denser-blog:
    image: registry.gitlab.syncad.com/hive/denser/blog:${VERSION:?VERSION required}
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
    volumes:
      - ${ENV_FILE:?ENV_FILE must be set}:/app/apps/.env:ro
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      rollback_config:
        order: start-first
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:3000/trending']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  denser-wallet:
    image: registry.gitlab.syncad.com/hive/denser/wallet:${VERSION:?VERSION required}
    ports:
      - '4000:3000'
    environment:
      PORT: 3000
    volumes:
      - ${ENV_FILE:?ENV_FILE must be set}:/app/apps/.env:ro
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      rollback_config:
        order: start-first
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:3000/']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
