import { expect, type Locator, type Page } from '@playwright/test';
import { TIMEOUTS } from './constants';
import { PostPage } from './pages/postPage';

/**
 * Shared context for §6.2 Comment Voting fixture specs. Mirrors
 * postVotingContext.ts but operates on the first comment of a post
 * detail page rather than the first post on /trending.
 *
 * Voted-state pre-conditions (VOTE-C03/VOTE-C04) come from overlay
 * variants generated by `fixture-auth/generate-voted-variants.mjs` —
 * the variant generator pins the same comment that `.first()` resolves
 * to in the recorded fixture, so spec and overlay stay in sync.
 */

export const VOTER = process.env.CI_TEST_USER || 'guest4test';

/**
 * Post that hosts the comments under test. Same one used by
 * postDetail.spec, so we share the bridge.get_discussion shape and a
 * known comment tree. If you re-record commentVoting against a
 * different post, update these here AND in the variant generator.
 */
export const POST_COMMUNITY = 'hive-160391';
export const POST_AUTHOR = 'gtg';
export const POST_PERMLINK = 'hive-hardfork-25-jump-starter-kit';
export const POST_PATH = `/${POST_COMMUNITY}/@${POST_AUTHOR}/${POST_PERMLINK}/`;

/** Hive basis-points convention: 10000 = 100% upvote, -10000 = 100% downvote, 0 = remove. */
export const FULL_UPVOTE = 10000;
export const FULL_DOWNVOTE = -10000;
export const REMOVE_VOTE = 0;

/**
 * Navigate to the post detail page and wait for hydration to settle on
 * the logged-in branch. Without this, the comment cards re-render
 * through their anonymous (DialogLogin-wrapped) state and the click
 * lands on the login dialog instead of the vote handler.
 *
 * (Same race that `gotoTrendingLoggedIn` guards against, just on a
 * different page.)
 */
export async function gotoPostLoggedIn(page: Page): Promise<void> {
  await page.goto(POST_PATH, { waitUntil: 'domcontentloaded' });
  await expect(page.getByTestId('login-btn')).toBeHidden({
    timeout: TIMEOUTS.HYDRATION
  });
}

/**
 * Read author + permlink off the first rendered comment. The
 * timestamp link emits an in-page anchor `#@<author>/<permlink>`
 * (see comment-list-item.tsx). Used to keep the spec author/permlink
 * agnostic — `.first()` resolves to whatever the UI sorts to top, and
 * the broadcast assertion picks up the same identity from the DOM.
 */
export async function readFirstCommentIdent(
  postPage: PostPage
): Promise<{ author: string; permlink: string }> {
  const link = postPage.commentListItems
    .first()
    .locator('[data-testid="comment-timestamp-link"]')
    .first();
  const href = await link.getAttribute('href');
  const m = href?.match(/^#@([^/]+)\/(.+)$/);
  if (!m) {
    throw new Error(`Unexpected comment-timestamp-link href: ${href}`);
  }
  return { author: m[1], permlink: m[2] };
}

/** First comment's upvote button (the top-most rendered card-footer). */
export function firstCommentUpvoteButton(postPage: PostPage): Locator {
  return postPage.commentCardsFooterUpvotes.first();
}

/** First comment's downvote button. */
export function firstCommentDownvoteButton(postPage: PostPage): Locator {
  return postPage.commentCardsFooterDownvotes.first();
}

/**
 * Wait until the first comment's upvote icon shows the "already
 * upvoted" visual state. In both filled branches (upvote and downvote
 * VoteRemovalDialog wrappers in votes-component.tsx) the icon picks up
 * `cursor-pointer` and `text-white` — neither of which appears on the
 * fresh-state branches. We match on `text-white` as a complete class
 * token so it doesn't trip on `hover:` prefixed variants used in fresh
 * state.
 *
 * Until those tokens land the component is still in its pre-fetch
 * branch and a click would submit a fresh vote instead of opening the
 * VoteRemovalDialog. (Same `list_votes` race documented in
 * postVotingContext.)
 */
const FILLED_ICON_RE = /(?:^|\s)text-white(?:\s|$)/;

export async function expectFirstCommentUpvotedState(page: Page): Promise<void> {
  const postPage = new PostPage(page);
  await expect(
    firstCommentUpvoteButton(postPage).locator('svg')
  ).toHaveClass(FILLED_ICON_RE);
}

export async function expectFirstCommentDownvotedState(page: Page): Promise<void> {
  const postPage = new PostPage(page);
  await expect(
    firstCommentDownvoteButton(postPage).locator('svg')
  ).toHaveClass(FILLED_ICON_RE);
}
