services:
  denser-auth:
    profiles:
      - denser
    image: registry.gitlab.syncad.com/hive/denser/auth:${AUTH_IMAGE_TAG:-latest}
    environment:
      PORT: ${AUTH_PORT}
      REACT_APP_API_ENDPOINT: "https://${PUBLIC_HOSTNAME}:${API_HTTPS_PORT}"
      REACT_APP_IMAGES_ENDPOINT:
      REACT_APP_SITE_DOMAIN: "https://${PUBLIC_HOSTNAME}:${AUTH_PORT}"
      REACT_APP_CHAIN_ID:
      REACT_APP_LOGGING_BROWSER_ENABLED: "true"
      TURBO_APP_SCOPE: '@hive/auth'
      TURBO_APP_PATH: '/apps/auth'
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - docker
    extra_hosts:
      - ${PUBLIC_HOSTNAME}:host-gateway
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://$${HOSTNAME}:$${PORT}/ || exit 1']
      interval: 5s
      timeout: 5s
      retries: 5
    # depends_on:
    #   compose:
    #     condition: service_healthy
  caddy-auth:
    profiles:
      - denser
    image: caddy:2.7.6
    environment:
      PUBLIC_HOSTNAME:
      AUTH_PORT:
    command:
      - caddy
      - reverse-proxy
      - --from=https://${PUBLIC_HOSTNAME}:${AUTH_PORT}
      - --to=http://denser-auth:${AUTH_PORT}
      - --internal-certs
      - --disable-redirects
    networks:
      - docker
    ports:
      - '${AUTH_PORT}:${AUTH_PORT}'
    extra_hosts:
      - "${PUBLIC_HOSTNAME}:127.0.0.1"
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider https://$${PUBLIC_HOSTNAME}:$${AUTH_PORT}/ || exit 1']
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      denser-auth:
        condition: service_healthy