services:
  denser-blog:
    profiles:
      - denser
    image: registry.gitlab.syncad.com/hive/denser/blog:${BLOG_IMAGE_TAG:-latest}
    environment:
      PORT: ${BLOG_PORT:-3000}
      REACT_APP_API_ENDPOINT: "https://${PUBLIC_HOSTNAME}:${API_HTTPS_PORT}"
      REACT_APP_IMAGES_ENDPOINT:
      REACT_APP_SITE_DOMAIN: "https://${PUBLIC_HOSTNAME}:${BLOG_PORT}"
      REACT_APP_WALLET_ENDPOINT: "https://${PUBLIC_HOSTNAME}:${WALLET_PORT}"
      REACT_APP_CHAIN_ID:
      REACT_APP_LOGGING_BROWSER_ENABLED: "true"
      TURBO_APP_SCOPE: '@hive/blog'
      TURBO_APP_PATH: '/apps/blog'
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - docker
    extra_hosts:
      - ${PUBLIC_HOSTNAME}:host-gateway  
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://$${HOSTNAME}:$${PORT}/ || exit 1']
      interval: 5s
      timeout: 5s
      retries: 5
    # depends_on:
    #   compose:
    #     condition: service_healthy