import { type Page } from '@playwright/test';

/**
 * The editor's image-upload path POSTs the file to the configured
 * `REACT_APP_IMAGES_ENDPOINT` (default `https://images.hive.blog/`)
 * with a path of `<owner>/<challenge-signature>`. The fixture proxy
 * doesn't see those — they hit a different origin — so we install a
 * dedicated `page.route` to canned-respond with a deterministic URL
 * per upload.
 *
 * Mechanism:
 *   - Match any POST to `images.hive.blog/<anything>/<anything>`.
 *   - Return JSON `{ url: <synth url with sequential index> }`.
 *
 * This lets POST-08/09/18 specs exercise the editor's upload flow
 * (toolbar button, drag&drop, multi-image cover picker) end-to-end
 * without network and without requiring a real imagehoster signing
 * roundtrip on the chain side.
 */
export interface ImageUploadStub {
  /** URLs returned to the editor, in upload order. */
  uploadedUrls: string[];
  /** How many uploads were intercepted. */
  count: () => number;
}

export async function installImageUploadStub(page: Page): Promise<ImageUploadStub> {
  const uploadedUrls: string[] = [];

  await page.route(
    /https?:\/\/(www\.)?images\.hive\.blog\/[^/]+\/[^/?#]+/,
    async (route) => {
      if (route.request().method() !== 'POST') return route.continue();
      const idx = uploadedUrls.length + 1;
      const url = `https://images.hive.blog/p/QmFixture${idx}TestImage`;
      uploadedUrls.push(url);
      console.log(`[upload-stub] POST ${route.request().url().slice(0, 80)}… → ${url}`);
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ url })
      });
    }
  );

  return {
    uploadedUrls,
    count: () => uploadedUrls.length
  };
}

/**
 * Minimal valid 1×1 transparent PNG (68 bytes). Enough to satisfy any
 * "is this a recognised image format" check in the upload pipeline
 * (HEIC/HEIF detection, etc.) without bloating the repo with a real
 * binary asset. Tests pass this as the `buffer` to
 * `Locator.setInputFiles({ name, mimeType, buffer })`.
 *
 * Generated bytes match the canonical PNG layout: 8-byte signature,
 * IHDR (1×1, bit depth 8, RGBA), IDAT with one zlib-compressed RGBA
 * pixel, IEND.
 */
export const TINY_PNG = Buffer.from(
  '89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489' +
    '0000000b49444154789c6360000200000500017a5eab3f0000000049454e44ae426082',
  'hex'
);
