import type {RendererPlugin} from './RendererPlugin';

/**
 * Lightweight plugin that handles dynamic height resizing for Instagram embed iframes.
 * Listens for postMessage events from instagram.com/embed/ pages and adjusts iframe height.
 * Works with iframes generated by InstagramEmbedder.
 */
export class InstagramResizePlugin implements RendererPlugin {
    name = 'instagram-resize';

    onMount = (rootElement: HTMLElement): (() => void) | undefined => {
        if (typeof window === 'undefined') return undefined;

        let rafId: number | null = null;
        let lastEvent: MessageEvent | null = null;

        const processResize = () => {
            const event = lastEvent;
            lastEvent = null;
            rafId = null;
            if (!event) return;
            try {
                const data = typeof event.data === 'string' ? JSON.parse(event.data) : event.data;
                const height = data?.details?.height ?? data?.height ?? data?.params?.height;
                if (!height || typeof height !== 'number' || height < 100) return;
                const iframes = rootElement.querySelectorAll('.instagramWrapper iframe');
                iframes.forEach((iframe) => {
                    if (!(iframe instanceof HTMLIFrameElement)) return;
                    if (iframe.contentWindow === event.source) {
                        iframe.style.height = `${height}px`;
                    }
                });
            } catch {
                // Not a JSON message from Instagram, ignore
            }
        };

        const handleResize = (event: MessageEvent) => {
            if (event.origin !== 'https://www.instagram.com' && event.origin !== 'https://instagram.com') return;
            lastEvent = event;
            if (rafId === null) {
                rafId = requestAnimationFrame(processResize);
            }
        };

        window.addEventListener('message', handleResize);

        return () => {
            window.removeEventListener('message', handleResize);
            if (rafId !== null) cancelAnimationFrame(rafId);
        };
    };
}
